### PR TITLE
CICD

### PR DESCRIPTION
**Pull request by garrettux**
basically upon every commit, travis will:

* spin up a rethinkdb container on the travis build worker
* `docker build` the website image
* `docker run` the fresh image
* run curl against the website image end ensure it returns an HTTP 200

If all that works, it will push the website image to AWS Container Registry, and trigger a deployment to deploy the new image to the staging site at http://bantam-breaks-website-alb-693583480.us-east-1.elb.amazonaws.com/

### CODE REVIEW

**Comment by alsoscotland** [comment]
Travis build fails.  Looking at the logs the node version looks weird.  We need >10 and we are getting 0.10.x

**Comment by garrettux** [comment]
yeah the build is failing because the `src/config.js` either ignores or doesn’t see the env var for `RETHINKDB_HOST`

**Comment by garrettux** [comment]
the node version thing is from the node on the travis worker, not in the docker image.  shouldn't affect anything

**Comment by garrettux** [comment]
build #40 failed because we got throttled by dockerhub or sometehing.  https://travis-ci.org/the-bantam-breaks/breaks-website/builds/541352981 passed

**Pull request merged**
